# frozen_string_literal: true

module Eccairs
  module Entities
    class Occurrence < Eccairs::Base::Entity
      entity_id "24"
      xml_tag "Occurrence"

      # Direct occurrence attributes
      has_many :air_temperature, class_name: "Eccairs::Attributes::AirTemperature"
      has_many :atm_contribution, class_name: "Eccairs::Attributes::AtmContribution"
      has_many :authority_occ_closure, class_name: "Eccairs::Attributes::AuthorityOccClosure"
      has_many :aviation_sector, class_name: "Eccairs::Attributes::AviationSector"
      has_many :cloud_amount, class_name: "Eccairs::Attributes::CloudAmount"
      has_many :damage_not_to_a_c, class_name: "Eccairs::Attributes::DamageNotToAC"
      has_many :dang_goods_involved, class_name: "Eccairs::Attributes::DangGoodsInvolved"
      has_many :detection_phase, class_name: "Eccairs::Attributes::DetectionPhase"
      has_many :dew_point, class_name: "Eccairs::Attributes::DewPoint"
      has_many :effect_on_atm_service, class_name: "Eccairs::Attributes::EffectOnAtmService"
      has_many :file_number, class_name: "Eccairs::Attributes::FileNumber"
      has_many :ground_repeatability, class_name: "Eccairs::Attributes::GroundRepeatability"
      has_many :ground_severity, class_name: "Eccairs::Attributes::GroundSeverity"
      has_many :ground_severity_applied, class_name: "Eccairs::Attributes::GroundSeverityApplied"
      has_many :headline, class_name: "Eccairs::Attributes::Headline"
      has_many :height_of_cloud_base, class_name: "Eccairs::Attributes::HeightOfCloudBase"
      has_many :highest_damage, class_name: "Eccairs::Attributes::HighestDamage"
      has_many :injury_level, class_name: "Eccairs::Attributes::InjuryLevel"
      has_many :latitude_of_occ, class_name: "Eccairs::Attributes::LatitudeOfOcc"
      has_many :light_conditions, class_name: "Eccairs::Attributes::LightConditions"
      has_many :local_date, class_name: "Eccairs::Attributes::LocalDate"
      has_many :local_time, class_name: "Eccairs::Attributes::LocalTime"
      has_many :location_name, class_name: "Eccairs::Attributes::LocationName"
      has_many :longitude_of_occ, class_name: "Eccairs::Attributes::LongitudeOfOcc"
      has_many :maximum_gust, class_name: "Eccairs::Attributes::MaximumGust"
      has_many :object_damaged, class_name: "Eccairs::Attributes::ObjectDamaged"
      has_many :occurrence_category, class_name: "Eccairs::Attributes::OccurrenceCategory"
      has_many :occurrence_class, class_name: "Eccairs::Attributes::OccurrenceClass"
      has_many :occurrence_status, class_name: "Eccairs::Attributes::OccurrenceStatus"
      has_many :overall_repeatability, class_name: "Eccairs::Attributes::OverallRepeatability"
      has_many :overall_severity, class_name: "Eccairs::Attributes::OverallSeverity"
      has_many :overall_severity_applied, class_name: "Eccairs::Attributes::OverallSeverityApplied"
      has_many :responsible_entity, class_name: "Eccairs::Attributes::ResponsibleEntity"
      has_many :spec_tech_repeatability, class_name: "Eccairs::Attributes::SpecTechRepeatability"
      has_many :spec_tech_severity, class_name: "Eccairs::Attributes::SpecTechSeverity"
      has_many :spec_tech_severity_applied, class_name: "Eccairs::Attributes::SpecTechSeverityApplied"
      has_many :speed_measured_at, class_name: "Eccairs::Attributes::SpeedMeasuredAt"
      has_many :state_area_of_occ, class_name: "Eccairs::Attributes::StateAreaOfOcc"
      has_many :third_party_damage, class_name: "Eccairs::Attributes::ThirdPartyDamage"
      has_many :total_fatalities_ground, class_name: "Eccairs::Attributes::TotalFatalitiesGround"
      has_many :total_injuries_ground, class_name: "Eccairs::Attributes::TotalInjuriesGround"
      has_many :total_minor_injuries_ground, class_name: "Eccairs::Attributes::TotalMinorInjuriesGround"
      has_many :total_on_board_a_c, class_name: "Eccairs::Attributes::TotalOnBoardAC"
      has_many :total_serious_injuries_ground, class_name: "Eccairs::Attributes::TotalSeriousInjuriesGround"
      has_many :utc_date, class_name: "Eccairs::Attributes::UtcDate"
      has_many :utc_time, class_name: "Eccairs::Attributes::UtcTime"
      has_many :visibility, class_name: "Eccairs::Attributes::Visibility"
      has_many :weather_relevant, class_name: "Eccairs::Attributes::WeatherRelevant"
      has_many :wind_direction, class_name: "Eccairs::Attributes::WindDirection"
      has_many :wind_gusts, class_name: "Eccairs::Attributes::WindGusts"
      has_many :wind_speed, class_name: "Eccairs::Attributes::WindSpeed"
      has_many :wx_conditions, class_name: "Eccairs::Attributes::WxConditions"

      # Nested entities
      has_many :aircraft, class_name: "Eccairs::Entities::Aircraft"
      has_many :aerodrome_general, class_name: "Eccairs::Entities::AerodromeGeneral"
      has_many :air_navigation_service, class_name: "Eccairs::Entities::AirNavigationService"
      has_many :air_space, class_name: "Eccairs::Entities::AirSpace"
      has_many :dangerous_goods, class_name: "Eccairs::Entities::DangerousGoods"
      has_many :events, class_name: "Eccairs::Entities::Events"
      has_many :ground_handling, class_name: "Eccairs::Entities::GroundHandling"
      has_one :narrative, class_name: "Eccairs::Entities::Narrative"
      has_many :precipitation_and_other_weather_phenomena, class_name: "Eccairs::Entities::PrecipitationAndOtherWeatherPhenomena"
      has_many :reporting_history, class_name: "Eccairs::Entities::ReportingHistory"
      has_many :risk_assessment, class_name: "Eccairs::Entities::RiskAssessment"
      has_many :separation, class_name: "Eccairs::Entities::Separation"
    end
  end
end

