attribute_id: '1116'
xml_tag: GH_Organisation
sequence: 1
values:
  1: Acciona
  2: Atlántica de Handling
  3: Aviapartner
  4: Aviation Services
  5: Cepsa
  6: CLH Aviación
  7: CMD Aeropuertos
  8: dnata
  9: EASY Jet
  10: European Air Transport (DHL)
  11: Fraport Ground Services
  12: Groundforce
  13: Groundlink
  14: Iberia Airport Services
  15: Jet2.com
  16: LESMA Handling
  17: Marconi Handling
  18: Menzies Aviation
  19: Multiservicios Aeropurtuarios
  20: Newrest
  21: Norwegian
  22: Rentevic
  23: Ryanair
  24: SAS Ground Services (SGS)
  25: Servicios Logísticos de Combustibles de Aviación
  26: Skytanking
  27: Spanish intoplane Services
  28: Swiftair
  29: Swissport
  30: Terminales Canarios
  31: Translimp
  32: United Parcel Services (UPS)
  33: Worldwide Flight Services
  34: Other
  35: Unknown
