attribute_id: '492'
xml_tag: Make_Of_Propeller
sequence: 0
values:
  1: ADVANCE RATIO DESIGN CO
  2: AEROCOMPOSITE CO
  3: AIRFORCE
  4: ARROWPROP CO
  5: AUTERROTECH
  6: AVIA HAMILTON STANDARD AVIATION LTD
  7: AVIATION PROPELLERS INC
  8: DART AERO ACESSORIES INC
  9: DOWTY AEROSPACE PROPPELLERS
  10: DOWTY PROPELLERS
  11: EVRA
  12: GENERAL NUCLEONICS INC
  13: HALTER UAV PROPELLERS
  14: HAMILTON STANDARD
  15: HARTZELL PROPELLER INC.
  16: HOFFMANN PROPELLER GMBH
  17: MCCAULEY ACCESSORY DIV
  18: MPPE
  19: MT-PROPELLER ENTWICKLUNG GMBH
  20: PERFECTUS AIRSREW PTYLTD
  21: PIGNOLO SA
  22: RATIER-FIGEAC
  23: ST. CROIX AIRCRAFT
  24: SENSENICH
  25: WALTER BORN
  26: WESTERN PROPELLER CO LTD
  98: OTHER
  99: UNKNOWN
  100: A/C DESIGN AND CERTIFICATION
  101: AERO AT SP. Z.O.O.
  102: ALES KREMEN
  103: ALEXANDER SCHLEICHER
  104: AMS-FLIGHT D.O.O.
  105: AVIA PROPELLER LTD.
  106: BINDER MOTORENBAU GMBH
  107: DG FLUGZEUGBAU GMBH
  108: FISCHER UND ENTWICKLUNGEN
  109: GE AVIATION SYSTEMS LTD
  110: GEFA-FLUG GMBH
  111: GT PROPELLERS S.N.C.
  112: HAMILTON SUNDSTRAND CORP.
  113: LANGE AVIATION GMBH
  114: LOM PRAHA S.P.
  115: MCCAULEY PROPELLER SYSTEMS
  116: PRODUCTION EVRA
  117: PZL WARSZAWA-OKECIE S.A.
  118: R. HUNT PROPELLER
  119: SENSENICH PROPELLER MANUF.
  120: SENSENICH WOOD PROPELLER CO.
  121: SOCIETE DUC
  122: SPORTINE AVIACIJA IR KO
  123: STEMME AG
  124: TECHNOFLUG LEICHTFLUGZEUGBAU
