attribute_id: '658'
xml_tag: Manufacturer
sequence: 3
values:
  1: Other
  2: AB Aircontainer A.C.
  3: ACEP - Advanced Composits Engineering + Production GmbH
  4: ACSS - Aviation Communication & Surveillance Systems, LLC
  5: AFDS 3
  6: AOA apparatebau gauting GmbH
  7: APIC
  8: AXITUDE S.r.l.
  9: Acro Aircraft Seating Ltd
  10: AeMaC (Aircraft Equipment Maintenance and Consulting)
  11: Aerazur
  12: Aero Net
  13: AeroAntenna Technology, Inc.
  14: Aerobox Composite Structures
  15: Aerodata AG
  16: Aerodyne Research
  17: Aeropack S.A.
  18: Aerosila
  19: Air Précision SAS
  20: AirPlus Maintenance GmbH
  21: Airbus Hamburg EGLG
  22: Aircraft Interior Products
  23: Alcan Singen GmbH
  24: AmSafe Bridport Limited T/A AmSafe Bridport
  25: Artex Aircraft Supplies, Inc.
  26: Aviointeriors S.p.A.
  27: Avionik Straubing GmbH
  28: Avtech Corporation
  29: B/E Aerospace (UK) Ltd
  30: B/E Aerospace Inc.
  31: BIRDY
  32: Barco n.v.
  33: Becker Flugfunkwerk GmbH
  34: Boeing Commercial Airlines / Global Partners
  35: Brice Manufacturing Co.
  36: Bridgestone Corporation
  37: British Airways
  38: Brüggemann GmbH & Co. KG
  39: C.N.S. Systems AB
  40: CIMSA Ingenieria de Sistemas, S.A.
  41: Caledonian Airborne Systems
  42: Chelton (Electrostatics) Limited
  43: Chelton Antenna S.A.
  44: Chelton Avionics, Inc. dba Wulfsberg Electronics
  45: Chelton Flight Systems
  46: Cirrus Technik GmbH
  47: DAe Systems GmbH
  48: DME Corporation
  49: DR&D Industries
  50: Dayton-Granger, Inc.
  51: DeCrane Aircraft Seating Company, Inc.
  52: DoKaSch GmbH
  53: Driessen Aircraft Interior Systems (Europe) BV
  54: Dunlop Aerospace Ltd, T/T Dunlop Aerospace Braking Systems
  55: Dunlop Aircraft Tyres Limited
  56: EADS Deutschland GmbH
  57: EADS Sogerma Services
  58: EAE electronics GmbH
  59: ECT Industries
  60: ELTA SA
  61: Eastern Aero Marine (EAM)
  62: Eaton Limited
  63: Embex
  64: Envirotainer Engineering AB
  65: Essex PB&R Corporation
  66: Euro Telematik AG
  67: EuroAvionics Navigationssysteme GmbH & Co. KG
  68: FAST Aero Space Technologies AG
  69: FRC Component Products Inc.
  70: Filser Electronic GmbH
  71: Firebird GmbH & Co. KG
  72: Fischer + Entwicklungen GmbH & Co KG
  73: Flight Components AG
  74: Flying Service Engineering & Equipment Ltd
  75: Franklin Products Ltd
  76: FreeFlight Systems
  77: G&L Technology Ltd
  78: GE Aviation (formerly Smiths Aerospace)
  79: GE Sensing (Druck Ltd.)
  80: GEMELLI S.r.I.
  81: GITA Aviation (Changzhou) Co. Ltd.
  82: GPI
  83: Gables Engineering Inc.
  84: Garmin AT, Inc.
  85: Garmin International
  86: Garrecht Avionik GmbH
  87: Geven SrL
  88: Goodrich Avionics Systems, Inc.
  89: Goodrich Power Systems
  90: Goodyear (Thailand) PCL
  91: Greiner PURtec GmbH
  92: Grupo Antolin Transport
  93: HR Smith (Technical Developments) Ltd
  94: Hamilton Sundstrand Power Systems
  95: Heinrich Mertens
  96: Helly Hansen Spesialprodukter AS
  97: Hoffmann Air Cargo Equipment GmbH
  98: Holmberg GmbH & Co. KG
  99: Honeywell ASCa Inc
  100: Honeywell Commercial Aviation Products
  101: Honeywell Engines Systems & Services
  102: Honeywell Grimes Aerospace Company
  103: Honeywell International Inc. (Glendale)
  104: Honeywell International Inc. (Olathe)
  105: Honeywell International Inc. (Phoenix)
  106: Honeywell International Inc. (Redmond)
  107: Hoover Industries
  108: ISOTH`AIR
  109: Ing. Büro Lang
  110: Innovint Aircraft Interior
  111: Intertechnique
  112: Ipeco Holdings Limited
  113: KLM
  114: L`Hotellier
  115: L-3 Communications Aviation Recorders
  116: L-3 Communications Avionics Systems Inc.
  117: LITEF GmbH
  118: MARTEC SERPE-IESM
  119: MICHELIN - LPAV
  120: MIKROTECHNA PRAHA a.s
  121: MITAS a.s.
  122: MarS a.s.
  123: Marc Ingegno
  124: Martin Baker Aircraft Company Ltd
  125: Meggitt Aerospace Ltd. T/A Meggitt Aircraft Braking Systems
  126: Meggitt Avionics
  127: Messier Bugatti
  128: Microturbo
  129: Mid-Continent Instruments
  130: NEC
  131: Nordisk Aviation Products a.s
  132: Northern Airborne Technology Ltd.
  133: PARACHUTES DE FRANCE S.A
  134: PARAFUN
  135: PRONAL
  136: PS Engineering Inc
  137: PalNet GmbH Air Cargo Products
  138: Paratec Fallschirmbau-Technik-Service-Vertrieb GmbH
  139: Patmos Engineering Services, Inc.
  140: Penny & Giles Aerospace Ltd
  141: Performance Designs Inc
  142: Pratt & Whitney Canada
  143: Premium Aircraft Interiors UK Ltd. T/A Contour Premium Aircraft Seating
  144: Prvni brenská strojirna Velká Bites a.s.
  145: REVUE THOMMEN AG
  146: RFD Beaufort Ltd.
  147: RTX telecom A/S
  148: Raytheon Systems Limited
  149: Recaro Aircraft Seating GmbH & Co
  150: Regent Aerospace
  151: Ribeco Frachtgeräte GmbH
  152: Rockwell Collins France
  153: Rockwell Collins Inc.
  154: Rohde & Schwarz GmbH & Co. KG
  155: Rohde & Schwarz Messgerätebau GmbH
  156: Ryan International Corporation
  157: Röder Präzision GmbH
  158: SAAB AB (Publ)
  159: SAAB Avitronics
  160: SAGEM DEFENSE SECURITE
  161: SERPE-IESM
  162: SICMA AERO SEAT
  163: SIRS Navigation Ltd.
  164: Sandel Avionics, Inc.
  165: Schroth Safety Products GmbH
  166: Selex Communications S.p.A.
  167: Sennheiser electronic GmbH&Co. KG
  168: Septentrio Satellite Navigation
  169: Shark Sports Ltd T/A Shark Group
  170: Siemens S.A.S.
  171: Sigma Tec, Inc.
  172: Signature Industries
  173: Singapore Jamco Pte Ltd
  174: Skyforce Avionics Ltd
  175: Smiths Aerospace
  176: Spekon Sächsische Spezialkonfektion GmbH
  177: Stauff Systec GmbH
  178: Sun Path Products Inc.
  179: Survitec Group Limited t/a RFD Beaufort
  180: TEAM
  181: TECNOBIT S.L
  182: THERMOCOAX
  183: TL elektronic Inc.
  184: Telair International
  185: Telephonics
  186: Terma A/S
  187: Thales Avionics Electrical Systems
  188: Thales Avionics Limited
  189: Thales Avionics S.A.
  190: Thales Communications S.A.
  191: Thielert Aircraft Engines GmbH
  192: Trans-Cal Industries, Inc.
  193: Trig Avionics Limited
  194: UUDS AERO
  195: Universal Avionics Systems Corporation
  196: VIKING LIFE-SAVING EQUIPMENT A/S
  197: Van Riemsdijk Rotterdam b.v
  198: Walter Dittel Luftfahrtgerätebau
  199: Weber Aircraft LP
  200: Werthenbach Hydraulik Antriebstechnik GmbH
  201: Wulfsberg Fliteline
  202: Diamond Aircraft Industries GmbH
  203: MSW GmbH
  204: BRP-Rotax GmbH & Co KG
  205: Air Ambulance Technology Gesellschaft m.b.H.
  206: KTS-Peter Sporrer Handelsagentur für Kabeltechnik
  207: Pankl Aerospace Systems Europe GmbH
  208: Austro Engine GmbH
  209: HB-Flugtechnik GesmbH
  210: Helikopter Air Transport Gesellschaft m.b.H.
  211: AMES Production and Logistic Services GmbH
  212: RO-RA Aviation Systems GmbH
  213: F. LIST GmbH
  214: MAGNA STEYR Fahrzeugtechnik AG & CO KG
  215: Peak Technology GmbH
  216: System 7 Metal Technology GmbH
  217: Airborne Technologies GmbH
  218: TEST-FUCHS Aerospace Systems GmbH
  219: SCOTTY Group Austria GmbH
  220: GITA Aviation (Changzhou) Co. Ltd
  221: HBL Power Systems, Ltd.
  222: KORITA AVIATION (SUZHOU) CO., LTD.
  223: Egret Aviation Co., Ltd
  224: Tata Advanced Systems Ltd.
