---
attribute_id: '430'
xml_tag: Occurrence_Category
sequence: 14
values:
  1: 'AMAN: Abrupt maneuvre'
  2: 'ARC: Abnormal runway contact'
  3: 'CFIT: Controlled flight into or toward terrain'
  4: 'EVAC: Evacuation'
  5: 'F-NI: Fire/smoke (non-impact)'
  6: 'F-POST: Fire/smoke (post-impact)'
  7: 'FUEL: Fuel related'
  8: 'RAMP: Ground Handling'
  9: 'GCOL: Ground Collision'
  10: 'ICE: Icing'
  11: 'LALT: Low altitude operations'
  12: 'LOC-G: Loss of control - ground'
  13: 'LOC-I: Loss of control - inflight'
  14: 'MAC: Airprox/ACAS alert/loss of separation/(near) midair collisions'
  15: 'RE: Runway excursion'
  18: 'SCF-NP: System/component failure or malfunction [non-powerplant]'
  19: 'SCF-PP: powerplant failure or malfunction'
  20: 'SEC: Security related'
  21: 'TURB: Turbulence encounter'
  22: 'USOS: Undershoot/overshoot'
  23: 'WSTRW: Windshear or thunderstorm'
  24: 'ADRM: Aerodrome'
  25: 'ATM: ATM/CNS'
  26: 'CABIN: Cabin safety events'
  27: 'WILD: Collision Wildlife'
  28: 'RI: Runway incursion - vehicle, aircraft or person'
  29: 'BIRD: Birdstrike'
  98: 'OTHR: Other'
  99: 'UNK: Unknown or undetermined'
  100: 'UIMC: Unintended flight in IMC'
  101: 'EXTL: External load related occurrences'
  102: 'CTOL: Collision with obstacle(s) during take-off and landing'
  103: 'LOLI: Loss of lifting conditions en-route'
  104: 'GTOW: Glider towing related events'
  105: 'MED: Medical'
  106: 'NAV: Navigation error'
