attribute_id: '1091'
xml_tag: Reporter_S_Language
sequence: 18
values:
  1: Afrikaans
  2: Albanian
  3: Arabic
  4: Armenian
  5: Azerbaijani
  6: Basque
  7: Belarusian
  8: Bulgarian
  9: Catalan
  10: Chinese
  11: Croatian
  12: Czech
  13: Danish
  14: Divehi
  15: Dutch
  16: English
  17: Estonian
  18: Faroese
  19: Finnish
  20: French
  21: Galician
  22: Georgian
  23: German
  24: Greek
  25: Gujarati
  26: Hebrew
  27: Hindi
  28: Hungarian
  29: Icelandic
  30: Indonesian
  31: Italian
  32: Japanese
  33: Kannada
  34: Kazakh
  35: Kirghiz
  36: Korean
  37: Latvian
  38: Lithuanian
  39: Macedonian
  40: Malay
  41: Marathi
  42: Mongolian
  43: Norwegian
  44: Persian
  45: Polish
  46: Portuguese
  47: Punjabi
  48: Romanian
  49: Russian
  50: Sanskrit
  51: Serbian
  52: Slovak
  53: Slovenian
  54: Spanish
  55: Swedish
  56: Tamil
  57: Tatar
  58: Telugu
  59: Thai
  60: Turkish
  61: Ukrainian
  62: Unknown
  63: Urdu
  64: Uzbek
  65: Vietnamese
  66: Other
