---
attribute_id: '557'
xml_tag: Traffic_Variation_Before_Supervisor
sequence:
values:
  1: Increasing slowly
  2: Increasing rapidly
  3: Decreasing slowly
  4: Decreasing rapidly
  5: No variation
  99: Unknown
