name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby (mise)

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Run the default task
        run: mise exec -- bundle exec rake
